# Gitpod workspace config for PANGI (Solana + Anchor + Next.js)
image:
  file: .gitpod.Dockerfile

# Ports we care about
ports:
  - port: 3000        # Next.js app
    onOpen: open-preview
  - port: 8899        # solana-test-validator JSON-RPC
    onOpen: ignore
  - port: 8900        # solana-test-validator WebSocket
    onOpen: ignore
  - port: 9900        # faucet
    onOpen: ignore

# Prebuilds (optional but recommended)
# Enable in GitHub app settings for your repo
# github:
#   prebuilds:
#     master: true
#     branches: true
#     pullRequests: true

tasks:
  - name: Install toolchain & deps
    init: |
      ./scripts/install-solana-anchor.sh
      pnpm install || yarn install || npm install
      # Copy IDLs if using Anchor target output
      if [ -f ./scripts/generate-idl.sh ]; then bash ./scripts/generate-idl.sh || true; fi
    command: |
      ./scripts/gitpod-post-init.sh
      echo "Workspace ready. Try: solana --version && anchor --version"

  - name: Dev server
    command: |
      if [ -d app/web ] || [ -f package.json ]; then         echo "Starting Next.js on port 3000" &&         (cd app/web 2>/dev/null || true);         if command -v pnpm >/dev/null 2>&1; then pnpm dev;         elif command -v yarn >/dev/null 2>&1; then yarn dev;         else npm run dev; fi;       else         echo "No Next.js app found. Skipping.";       fi

  - name: Local validator (optional)
    command: |
      echo "Starting local validator (optional). Use devnet for shared tests." &&       solana-test-validator --reset --faucet-port 9900

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - streetsidesoftware.code-spell-checker
    - esbenp.prettier-vscode
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
