name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you thought about?
      placeholder: Describe alternative solutions

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Token Program
        - NFT Program
        - Vault Program
        - Distribution Program
        - SDK
        - Frontend (dApp)
        - IDL/Types
        - Scripts/Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking my work
        - Critical - Essential for project
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Examples from other projects or mockups
      placeholder: Links to similar features or screenshots

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information
      placeholder: Add any other context here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with project goals
          required: false
        - label: I am willing to help implement this
          required: false
